apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
  namespace: gs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clientapp
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - image: davidmachacek/davidsapp:latest
        name: clientapp
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /
            port: 8080