kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: gs
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/david.machacek@ibm.com/Documents/goodsamaritan/mnt"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: gs
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi