apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: gs
spec:
  replicas: 1
  serviceAccountName: postgre-svc-account
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: davidmachacek/postgres:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim