kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: gs
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/david.machacek@ibm.com/Documents/goodsamaritan/mnt"
---