kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-read-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-read-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-read-role
subjects:
  - kind: Group
    name: 2ec95fb1-5771-4934-92b4-6726a78d3011
    namespace: gs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gs-tester
  namespace: gs
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gs-tester-binding
  namespace: gs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gs-tester
subjects:
  - kind: Group
    name: 2ec95fb1-5771-4934-92b4-6726a78d3011
    namespace: gs