apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: registry