apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer
  namespace: gs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: offerapp
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: offerapp
        aadpodidbinding: aks-pod-to-sa
    spec:
      containers:
      - image: myregistrydavid.azurecr.io/offer:latest
        name: offercontainer
        env:
          - name: INFORMER_URL
            valueFrom:
              configMapKeyRef:
                name: offer-config
                INFORMER_URL: username
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080