apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: gs
  labels:
    app: client
data:
  SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
  SPRING_DATASOURCE_USERNAME: sa
  SPRING_DATASOURCE_PASSWORD: password