apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapp
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - image: davidmachacek/client:v1
        name: clientcontainer
        envFrom:
          - configMapRef:
              name: client-config
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /actuator/info
            port: 8080